services:
  - type: web
    name: text-to-audio-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 2 -b 0.0.0.0:$PORT main:app --timeout 120
    autoDeploy: true
